import type { DifficultyConfig } from './types';

/** Add a new entry here to add a difficulty — no code changes required. */
export const difficulties: readonly DifficultyConfig[] = [
  {
    id: 'easy',
    label: 'Recruit',
    description: 'Two slow sentinels to start, generous battery. Each wing adds another.',
    mazeSize: 8,
    robotCount: 2,
    robotSpeed: 0.85,
    robotDetectionRange: 11,
    robotFovDeg: 90,
    robotHearing: 0.8,
    suspicionGain: 0.8,
    lampBattery: 180,
    lampRange: 18,
    lampRecharge: 4,
    darknessLevel: 0.35,
    progression: {
      mazeSizeStep: 2, maxMazeSize: 19, robotCountStep: 1, maxRobots: 7,
      robotSpeedStep: 0.1, maxRobotSpeed: 1.3, batteryStep: -15, minBattery: 90, darknessStep: 0.05,
    },
  },
  {
    id: 'normal',
    label: 'Survivor',
    description: 'Four sentinels to start, a darker, larger lab. Each wing adds another.',
    mazeSize: 10,
    robotCount: 4,
    robotSpeed: 1,
    robotDetectionRange: 13,
    robotFovDeg: 100,
    robotHearing: 1,
    suspicionGain: 1,
    lampBattery: 120,
    lampRange: 16,
    lampRecharge: 2,
    darknessLevel: 0.55,
    progression: {
      mazeSizeStep: 2, maxMazeSize: 23, robotCountStep: 1, maxRobots: 10,
      robotSpeedStep: 0.12, maxRobotSpeed: 1.5, batteryStep: -10, minBattery: 60, darknessStep: 0.05,
    },
  },
  {
    id: 'hard',
    label: 'Hunted',
    description: 'Big maze, six fast hunters, the lamp barely recharges.',
    mazeSize: 13,
    robotCount: 6,
    robotSpeed: 1.15,
    robotDetectionRange: 15,
    robotFovDeg: 110,
    robotHearing: 1.2,
    suspicionGain: 1.3,
    lampBattery: 90,
    lampRange: 14,
    lampRecharge: 0.8,
    darknessLevel: 0.75,
    progression: {
      mazeSizeStep: 2, maxMazeSize: 25, robotCountStep: 1, maxRobots: 13,
      robotSpeedStep: 0.12, maxRobotSpeed: 1.65, batteryStep: -8, minBattery: 45, darknessStep: 0.04,
    },
  },
  {
    id: 'nightmare',
    label: 'Nightmare',
    description: 'Pitch black. Eight hunters. No recharge. They hear everything.',
    mazeSize: 16,
    robotCount: 8,
    robotSpeed: 1.3,
    robotDetectionRange: 17,
    robotFovDeg: 120,
    robotHearing: 1.5,
    suspicionGain: 1.6,
    lampBattery: 70,
    lampRange: 12,
    lampRecharge: 0,
    darknessLevel: 0.92,
    progression: {
      mazeSizeStep: 2, maxMazeSize: 27, robotCountStep: 1, maxRobots: 15,
      robotSpeedStep: 0.1, maxRobotSpeed: 1.75, batteryStep: -5, minBattery: 40, darknessStep: 0.02,
    },
  },
];
